name: "test build"
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  test-ubuntu:
    name: Testing ubuntu-latest
    runs-on: ubuntu-latest
    # https://kobzol.github.io/rust/ci/2021/05/07/building-rust-binaries-in-ci-that-work-with-older-glibc.html
    container: quay.io/pypa/manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: apt-get install -y install libclang-dev
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      #- run: sudo apt install -y gcc-multilib && rustup target install i686-unknown-linux-gnu

      - run: cargo build --release --examples --verbose #--target=i686-unknown-linux-gnu
      #- run: make test
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ubuntu-latest-exts
          path: |
            target/release/examples/libcharacters.*
            target/release/examples/libhello.*
            target/release/examples/libscalar.*
            target/release/examples/libseries.*
  test-macos:
    name: Testing macos-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --examples --verbose
      #- run: make test
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: macos-latest-exts
          path: |
            target/release/examples/libcharacters.*
            target/release/examples/libhello.*
            target/release/examples/libscalar.*
            target/release/examples/libseries.*
