name: "test build"
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  build-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --examples
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux_exts
          path: |
            target/debug/examples/libcharacters.so
            target/debug/examples/libhello.so
            target/debug/examples/libscalar.so
            target/debug/examples/libseries.so
  test-macos:
    name: Test on MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --examples
